title: Kushalava Reddy Yanala
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
<p align="center">
I'm working as Middleware Integration Specialist. 
Also learning the AI & ML courses from upGrad platoform.
Working with PSL company for 1 year. 
</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
